spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: nABxzwVdd9Ziahhcq3Ik
    initialization-mode: never #执行sql脚本
    schema: classpath:sql/schema.sql
