spring:
  profiles:
    active: redis-cluster
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: single-redis
  redis:
    port: 6379
    password:
    host: 10.211.55.5

---
spring:
  config:
    activate:
      on-profile: sentinel-redis
  redis:
    sentinel:
      master: mymaster
      nodes: 10.211.55.5:26379,10.211.55.5:26380,10.211.55.5:26381
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10

---
spring:
  config:
    activate:
      on-profile: redis-cluster
  redis:
    cluster:
      nodes: 10.211.55.4:8001,10.211.55.5:8002,10.211.55.6:8003,10.211.55.4:8004,10.211.55.5:8005,10.211.55.6:8006
    password: patrick
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max‐idle: 50
        min‐idle: 10
        max‐active: 100
        max‐wait: 1000

